export const AUTH_USER         = 'AUTH_USER';
export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const SOCKET_CONNECTED  = 'SOCKET_CONNECTED';
